FROM python:3.10

# set the working directory
WORKDIR /backend

# install dependencies
COPY ./requirements.txt /backend
RUN apt-get update 
RUN apt-get -y install libc-dev
RUN apt-get install build-essential -y
RUN pip install --no-cache-dir --upgrade -r requirements.txt

# start the server
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "80"]
